openapi: 3.1.0
info:
  title: Bijbelse Psalmen API
  version: "1.0"
servers:
  - url: https://<jouw-domain>.onrender.com
paths:
  /api/psalm:
    get:
      operationId: get_psalm_vers
      summary: Haal één berijmd psalmvers (1773)
      parameters:
        - name: psalm
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 150
        - name: vers
          in: query
          schema:
            type: integer
            minimum: 1
      responses:
        "200": 
          description: Psalmvers gevonden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PsalmVers'
        "404":
          description: Niet gevonden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/psalm/max:
    get:
      operationId: get_psalm_max
      summary: Geef maximaal versnummer in 1773-berijming
      parameters:
        - name: psalm
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 150
      responses:
        "200":
          description: Maximale versnummer
          content:
            application/json:
              schema:
                type: integer
        "404":
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    PsalmVers:
      type: object
      properties:
        psalm:
          type: integer
        vers:
          type: integer
        text:
          type: string
    Error:
      type: object
      properties:
        detail:
          type: string
  responses:
    NotFound:
      description: Niet gevonden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
